@startuml VacQ System Use Case Diagram
left to right direction
actor "User" as user
rectangle "Hotel Booking System" as VacQSystem {    
    usecase "Authentication" as authenHotels
    usecase "Register" as register
    usecase "View\nHotels" as viewHotels
    usecase "Manage\nBookings" as manageBooking
    usecase "Manage\nHotels" as manageHotels
}

user -- register
user -- viewHotels
user -- manageBooking
user -- authenHotels

actor "Admin" as admin
register -- admin
manageHotels -- admin
manageBooking -- admin
authenHotels -- admin

@enduml